config/routes.rb
Rails.application.routes.draw do
  resources :routine_exercises
  resources :routines do
    member do
      get :workout, to: "workouts#show"
    end
  end
  resources :exercises
  root "application#home"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/routine.rb
class Routine < ApplicationRecord
  has_many :routine_exercises
  has_many :exercises, through: :routine_exercises

  validates :name, presence: true, uniqueness: true
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  before_action :set_routine, only: %i[show edit update destroy]

  def index
    @routines = Routine.all
  end

  # GET /routines/1 or /routines/1.json
  def show; end

  # GET /routines/new
  def new
    @routine = Routine.new
  end

  # GET /routines/1/edit
  def edit
    @routine_exercise = RoutineExercise.new(routine: @routine)
  end

  # POST /routines or /routines.json
  def create
    @routine = Routine.new(routine_params)

    respond_to do |format|
      if @routine.save
        format.html { redirect_to @routine, notice: "Routine was successfully created." }
        format.json { render :show, status: :created, location: @routine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @routine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routines/1 or /routines/1.json
  def update
    respond_to do |format|
      if @routine.update(routine_params)
        format.html do
          redirect_to @routine, notice: "Routine was successfully updated.", status: :see_other
        end
        format.json { render :show, status: :ok, location: @routine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @routine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routines/1 or /routines/1.json
  def destroy
    @routine.destroy!

    respond_to do |format|
      format.html do
        redirect_to routines_path, notice: "Routine was successfully destroyed.", status: :see_other
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_routine
    @routine = Routine.find(params.expect(:id))
    weekday_order = <<~SQL.squish
      CASE LOWER(day_of_week)
        WHEN 'sunday' THEN 0
        WHEN 'monday' THEN 1
        WHEN 'tuesday' THEN 2
        WHEN 'wednesday' THEN 3
        WHEN 'thursday' THEN 4
        WHEN 'friday' THEN 5
        WHEN 'saturday' THEN 6
        ELSE 7
      END
    SQL

    @routine_exercises = @routine&.routine_exercises&.order(Arel.sql("(#{weekday_order})"), :order)
  end

  # Only allow a list of trusted parameters through.
  def routine_params
    params.expect(routine: [:name])
  end
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/views/routines/_exercises_table.html.erb
<%= pb_rails("table", props: { collapse: "sm" }) do %>
  <%= pb_rails("table/table_head") do %>
    <%= pb_rails("table/table_row") do %>
      <%= pb_rails("table/table_header", props: { text: "Exercise Name" }) %>
      <%= pb_rails("table/table_header", props: { text: "Day of Week" }) %>
      <%= pb_rails("table/table_header", props: { text: "Sets" }) %>
      <%= pb_rails("table/table_header", props: { text: "Reps" }) %>
      <%= pb_rails("table/table_header", props: { text: "Order" }) %>
      <%= pb_rails("table/table_header", props: { text: "Edit" }) %>
      <%= pb_rails("table/table_header", props: { text: "Delete" }) %>
    <% end %>
  <% end %>
  <%= pb_rails("table/table_body") do %>
    <% routine_exercises.each do |routine_exercise| %>
      <%= render "exercises_table_row", routine_exercise: routine_exercise %>
    <% end %>
  <% end %>
<% end %>

app/views/routines/_exercises_table_row.html.erb
<%= pb_rails("table/table_row") do %>
  <%= pb_rails("table/table_cell") do %>
    <%= routine_exercise.exercise.name %>
  <% end %>

  <%= pb_rails("table/table_cell") do %>
    <%= routine_exercise.day_of_week.titleize %>
  <% end %>

  <%= pb_rails("table/table_cell") do %>
    <%= routine_exercise.sets %>
  <% end %>

  <%= pb_rails("table/table_cell") do %>
    <%= routine_exercise.reps %> <%= routine_exercise.rep_unit %>
  <% end %>

  <%= pb_rails("table/table_cell") do %>
    <%= routine_exercise.order %>
  <% end %>

  <%= pb_rails("table/table_cell") do %>
    <%= link_to "Edit", edit_routine_exercise_path(routine_exercise) %>
  <% end %>

  <%= pb_rails('table/table_cell') do %>
    <%= button_to "Delete", routine_exercise, method: :delete %>
  <% end %>

<% end %>

app/views/routines/_form.html.erb
<%= pb_form_with(model: routine, local: true) do |form| %>
  <% if routine.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(routine.errors.count, "error") %> prohibited this routine from being saved:</h2>

      <ul>
        <% routine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.text_field :name, props: { label: true } %>

  <%= form.actions do |action| %>
    <%= action.submit %>
  <% end %>
<% end %>

app/views/routines/_routine_exercise_form.html.erb
<%= pb_rails('card', props: { padding: 'sm' }) do %>
  <%= pb_form_with(model: @routine_exercise, local: true) do |form| %>
    <%= form.hidden_field :routine_id, value: @routine.id %>

    <%= form.collection_select :exercise_id, Exercise.order(Arel.sql("LOWER(name)")), :id, :name, props: { label: "Exercise", blank_selection: 'Select an Exercise...' } %>

    <%= form.select :day_of_week, Date::DAYNAMES.each.map { |name| [name, name.downcase] }, props: { label: "Day of Week", blank_selection: 'Select a Day of Week...' } %>

    <%= form.number_field :order, props: { label: "Order", placeholder: "Enter order" } %>

    <%= form.number_field :sets, props: { label: "Sets", placeholder: "Enter sets" } %>

    <%= pb_rails('form_group') do %>
      <%= form.number_field :reps, props: { label: "Reps", placeholder: "Enter reps" } %>
      <%= form.text_field :rep_unit, props: { label: "Rep Unit", placeholder: "Enter rep unit" } %>
    <% end %>

    <%= form.actions do |action| %>
      <%= action.submit %>
    <% end %>
  <% end %>
<% end %>

app/views/routines/_routine_row.html.erb
<tr>
  <td><%= pb_rails("link", props: { text: routine.name, href: routine_path(routine) }) %></td>
  <td><%= pb_rails("button", props: { text: "Edit", aria: { label: "Edit Routine" }, tag: "a", link: edit_routine_path(routine), variant: 'secondary' }) %></td>
  <td>
    <%= pb_rails("button", props: { text: 'Delete', link: routine_path(routine), aria: { label: "Delete Routine" }, variant: 'danger', html_options: { 'data-method': 'delete' } }) %>
  </td>
  <td><%= pb_rails("button", props: { text: "Workout", aria: { label: "Begin Workout" }, tag: "a", link: workout_routine_path(routine), variant: 'secondary' }) %></td>
</tr>

app/views/routines/edit.html.erb
<% content_for :title, "Editing routine" %>

<%= pb_rails('title', props: {text: "Edit #{@routine.name}", tag: 'h1'}) %>

<%= render "form", routine: @routine %>

<%= pb_rails('title', props: {text: "Exercises", tag: 'h2'}) %>
<%= render "exercises_table", routine_exercises: @routine_exercises %>

<h3>Add Exercise To Routine</h3>
<%= render "routine_exercise_form" %>

<div>
  <%= link_to "Show this routine", @routine %> |
  <%= link_to "Back to routines", routines_path %>
</div>

app/views/routines/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Routines" %>

<%= pb_rails('flex', props: {justify: 'between'}) do %>
  <%= pb_rails('flex/flex_item') do %>
    <%= pb_rails('title', props: {tag: 'h1', text: 'Routines'}) %>
  <% end %>
  <%= pb_rails('flex/flex_item') do %>
    <%= pb_rails("button", props: { text: "New Routine", aria: { label: "New Routine" }, tag: "a", link: new_routine_path }) %>
  <% end %>
<% end %>

<%= pb_rails("table", props: { collapse: "sm" }) do %>
  <thead>
    <tr>
      <th>Name</th>
      <th>Edit</th>
      <th>Delete</th>
      <th>Workout</th>
    </tr>
  </thead>
  <tbody>
    <% @routines.each do |routine| %>
      <%= render "routine_row", routine: routine %>
    <% end %>
  </tbody>
<% end %>

app/views/routines/new.html.erb
<% content_for :title, "New routine" %>

<h1>New routine</h1>

<%= render "form", routine: @routine %>

<br>

<div>
  <%= link_to "Back to routines", routines_path %>
</div>

app/views/routines/show.html.erb
<p style="color: green"><%= notice %></p>

<%= pb_rails('title', props: {tag: 'h1', size: 1, text: @routine.name}) %>

<%= render 'exercises_table', routine_exercises: @routine_exercises %>

<div>
  <%= link_to "Edit this routine", edit_routine_path(@routine) %> |
  <%= link_to "Back to routines", routines_path %>

  <%= button_to "Destroy this routine", @routine, method: :delete %>
</div>