config/routes.rb
Rails.application.routes.draw do
  resources :routine_exercises
  resources :routines do
    member do
      get :workout, to: "workouts#show"
    end
  end
  resources :exercises
  root "application#home"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/routine_exercises_controller.rb
class RoutineExercisesController < ApplicationController
  before_action :set_routine_exercise, only: %i[show edit update destroy]

  def index
    @routine_exercises = RoutineExercise.all
  end

  def show; end

  def new
    @routine_exercise = RoutineExercise.new
  end

  def edit; end

  def create
    @routine_exercise = RoutineExercise.new(routine_exercise_params)

    if @routine_exercise.save
      redirect_to edit_routine_path(@routine_exercise.routine),
                  notice: "Routine exercise was successfully created."
    else
      redirect_to edit_routine_path(@routine_exercise.routine), status: :unprocessable_entity
    end
  end

  def update
    if @routine_exercise.update(routine_exercise_params)
      redirect_to routine_path(@routine_exercise.routine), notice: "Routine exercise was successfully updated.",
                                                           status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @routine = @routine_exercise.routine
    @routine_exercise.destroy!

    respond_to do |format|
      format.html do
        redirect_to routine_path(@routine), notice: "Routine exercise was successfully destroyed.",
                                            status: :see_other
      end
      format.json { head :no_content }
    end
  end

  private

  def set_routine_exercise
    @routine_exercise = RoutineExercise.find(params.expect(:id))
  end

  def routine_exercise_params
    puts params
    params.expect(routine_exercise: %i[routine_id exercise_id day_of_week order sets reps rep_unit])
  end
end

app/helpers/routine_exercises_helper.rb
module RoutineExercisesHelper
end

app/views/routine_exercises/_form.html.erb
<%= pb_form_with(model: routine_exercise) do |form| %>
  <% if routine_exercise.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(routine_exercise.errors.count, "error") %> prohibited this routine_exercise from being saved:</h2>

      <ul>
        <% routine_exercise.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :routine_id, style: "display: block" %>
    <%= form.text_field :routine_id %>
  </div>

  <div>
    <%= form.label :exercise_id, style: "display: block" %>
    <%= form.text_field :exercise_id %>
  </div>

  <div>
    <%= form.label :day_of_week, style: "display: block" %>
    <%= form.text_field :day_of_week %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/routine_exercises/_routine_exercise.html.erb
<div id="<%= dom_id routine_exercise %>">
  <p>
    <strong>Routine:</strong>
    <%= routine_exercise.routine_id %>
  </p>

  <p>
    <strong>Exercise:</strong>
    <%= routine_exercise.exercise_id %>
  </p>

  <p>
    <strong>Day of week:</strong>
    <%= routine_exercise.day_of_week %>
  </p>

</div>

app/views/routine_exercises/edit.html.erb
<% content_for :title, "Editing routine exercise" %>

<h1>Editing routine exercise</h1>

<%= render "form", routine_exercise: @routine_exercise %>

<br>

<div>
  <%= link_to "Show this routine exercise", @routine_exercise %> |
  <%= link_to "Back to routine exercises", routine_exercises_path %>
</div>

app/views/routine_exercises/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Routine exercises" %>

<h1>Routine exercises</h1>

<div id="routine_exercises">
  <% @routine_exercises.each do |routine_exercise| %>
    <%= render routine_exercise %>
    <p>
      <%= link_to "Show this routine exercise", routine_exercise %>
    </p>
  <% end %>
</div>

<%= link_to "New routine exercise", new_routine_exercise_path %>

app/views/routine_exercises/new.html.erb
<% content_for :title, "New routine exercise" %>

<h1>New routine exercise</h1>

<%= render "form", routine_exercise: @routine_exercise %>

<br>

<div>
  <%= link_to "Back to routine exercises", routine_exercises_path %>
</div>

app/views/routine_exercises/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @routine_exercise %>

<div>
  <%= link_to "Edit this routine exercise", edit_routine_exercise_path(@routine_exercise) %> |
  <%= link_to "Back to routine exercises", routine_exercises_path %>

  <%= button_to "Destroy this routine exercise", @routine_exercise, method: :delete %>
</div>